language: php

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

jobs:
  include:
  - stage: "Code quality"
    script: vendor/bin/phpcs --ignore=vendor,resources --standard=PSR12 .
    php: 7.2
  - stage: "Unit Testing"
    php:
      - '5.6'
      - '7.0'
      - '7.1'
      - '7.2'
      - '7.3'
    env:
      matrix:
        - TEST_SUITE=unit
    script: phpunit -c phpunit.xml.dist --testsuite $TEST_SUITE

stages:
  - "Code quality"
  - "Unit Testing"
