language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

env:
  matrix:
    - TEST_SUITE=unit

before_script:
  - composer install

script:
  - phpunit -c phpunit.xml.dist --testsuite $TEST_SUITE
