language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

env:
  matrix:
    - TEST_SUITE=unit

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

jobs:
  include:
  - stage: qa
    name: QA
    script: vendor/bin/phpcs --ignore=vendor,resources --standard=PSR12 .
    php: 7.2
  - stage: test
    name: Tests
    script: phpunit -c phpunit.xml.dist --testsuite $TEST_SUITE

stages:
  - qa
  - test
